In [1]:
#data libraries
import pandas as pd
import numpy as np

#visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use(style='ggplot')
plt.rcParams['figure.figsize'] = (10, 6)

%matplotlib inline

sns.set_style("whitegrid")

In [2]:
%%HTML
<style type="text/css">
table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}

In [3]:
#Reading training data
df_train = pd.read_csv(r'C:\Users\Vinay\Documents\Kaggle\Titanic_Sink\train.csv')

#Reading test data
df_test = pd.read_csv(r'C:\Users\Vinay\Documents\Kaggle\Titanic_Sink\test.csv')

In [4]:
# combining train and test values
data = pd.concat((df_train, df_test)).reset_index(drop=True)
x_Survived = df_train["Survived"]
data.drop(["Survived"], axis = 1, inplace= True)

In [5]:
data.drop('PassengerId', axis=1, inplace= True)

In [7]:
data.head(5)

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

#### Work in Progress for Fmailty Status

In [14]:
df_train['Name'].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [15]:
df_train['Family'] = df_train['Name'].apply(lambda x : x.split(',')[0])

In [16]:
df_train['Family'].value_counts()

Andersson    9
Sage         7
Panula       6
Johnson      6
Goodwin      6
            ..
Reynaldo     1
Behr         1
Pinsky       1
Aks          1
Turkula      1
Name: Family, Length: 667, dtype: int64

In [21]:
Family_data = df_train.groupby('Family').sum()['Survived']/df_train.groupby('Family').count()['Survived']

In [24]:
Family_data = pd.DataFrame(Family_data)

In [26]:
Family_data.reset_index(inplace= True)

In [34]:
Family_data.rename(columns= {'Survived' : 'Family_Sur_rate'}, inplace= True)

In [35]:
Family_data.head()

Family  Family_Sur_rate
0   Abbing              0.0
1   Abbott              0.5
2  Abelson              0.5
3    Adahl              0.0
4    Adams              0.0

In [31]:
data.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked     Family  
0      1      0         A/5 21171   7.2500   NaN        S     Braund  
1      1      0          PC 17599  71.2833   C85        C    Cumings  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      1      0            113803  53.1000  C123        S   Futrelle  
4      0      0            373450   8.0500   NaN        S      Allen

In [40]:
data = pd.merge(data, Family_data, on='Family')

In [41]:
data.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       3                          Braund, Mr. Lewis Richard    male  29.0   
2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3       1                          Cumings, Mr. John Bradley    male  39.0   
4       3                             Heikkinen, Miss. Laina  female  26.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked     Family  \
0      1      0         A/5 21171   7.2500   NaN        S     Braund   
1      1      0              3460   7.0458   NaN        S     Braund   
2      1      0          PC 17599  71.2833   C85        C    Cumings   
3      1      0          PC 17599  71.2833   C85        C    Cumings   
4      0      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen   

   Family_Sur_rate  
0              0.0  
1              0.0  
2              1.0  
3              1.0  
4              1.0

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1079 entries, 0 to 1078
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Pclass           1079 non-null   int64  
 1   Name             1079 non-null   object 
 2   Sex              1079 non-null   object 
 3   Age              873 non-null    float64
 4   SibSp            1079 non-null   int64  
 5   Parch            1079 non-null   int64  
 6   Ticket           1079 non-null   object 
 7   Fare             1079 non-null   float64
 8   Cabin            249 non-null    object 
 9   Embarked         1077 non-null   object 
 10  Family           1079 non-null   object 
 11  Family_Sur_rate  1079 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 109.6+ KB


In [43]:
#function to extract title
def extract_title(name) :
    string = name.split(',')[1].split(' ')[1]
    if '.' in string :
        return string[:-1]
    else :
        return string
    
#function to map other titles to standard title
def get_title(title, sex) :
    
    if title not in ['Mr', 'Mrs', 'Master', 'Miss'] :
        
        if title == 'the' :
            #The Countess implies we can use Mrs can be used
            return 'Mrs'
        elif title == 'Jonkheer':
            #The Jonkheer implies we can use Mr can be used
            return 'Mr'
        elif title == 'Mlle':
            return 'Miss'
        elif title == 'Ms':
            return 'Miss'
        elif title == 'Lady':
            return 'Mrs'
        else :
            if sex == 'male' :
                return 'Mr'
            else :
                return 'Mrs'
    else:
        return title
        
#impute age from title
def get_age(age, title) :
    
    if age != age :
        if title == 'Master' :
            return 5.00
        elif title == 'Miss'  :
            return 22.00
        elif title == 'Mr' :
            return 33.00
        else:
            return 36.00
    else :
        return age

In [44]:
data['Title'] = data['Name'].apply(extract_title)

In [45]:
data['Title'] = data.apply(lambda x : get_title(x.Title, x.Sex), axis=1)

In [46]:
data['Age'] = data.apply(lambda x : get_age(x.Age, x.Title), axis=1)

In [47]:
data[data['Fare'].isna()]

Empty DataFrame
Columns: [Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Family, Family_Sur_rate, Title]
Index: []

In [48]:
data[data['Embarked'].isna()]

Pclass                                       Name     Sex   Age  SibSp  \
148        1                        Icard, Miss. Amelie  female  38.0      0   
1034       1  Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   

      Parch  Ticket  Fare Cabin Embarked Family  Family_Sur_rate Title  
148       0  113572  80.0   B28      NaN  Icard              1.0  Miss  
1034      0  113572  80.0   B28      NaN  Stone              1.0   Mrs

In [49]:
data.groupby(['Pclass', 'Embarked']).mean()['Fare']

Pclass  Embarked
1       C           115.816893
        Q            90.000000
        S            73.495327
2       C            26.250200
        Q            12.350000
        S            21.406784
3       C            11.662354
        Q            11.070466
        S            15.244716
Name: Fare, dtype: float64

In [50]:
data.loc[1043, 'Fare'] = 14.43

In [51]:
data.loc[61, 'Embarked'] = 'S'
data.loc[829, 'Embarked'] = 'S'

In [52]:
data['Name_Length'] = data['Name'].apply(len)

In [53]:
data.drop(['Name', 'Ticket'], axis=1, inplace= True)

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1079 entries, 0 to 1078
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Pclass           1079 non-null   int64  
 1   Sex              1079 non-null   object 
 2   Age              1079 non-null   float64
 3   SibSp            1079 non-null   int64  
 4   Parch            1079 non-null   int64  
 5   Fare             1079 non-null   float64
 6   Cabin            249 non-null    object 
 7   Embarked         1077 non-null   object 
 8   Family           1079 non-null   object 
 9   Family_Sur_rate  1079 non-null   float64
 10  Title            1079 non-null   object 
 11  Name_Length      1079 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 149.6+ KB


In [55]:
categorical_features = ['Sex', 'Title']

features = pd.get_dummies(data[categorical_features], drop_first= True)

data = pd.concat([data.drop(categorical_features, axis=1), features], axis=1)

In [56]:
data.drop('Cabin', axis=1, inplace= True)

In [57]:
data.head(3)

Pclass   Age  SibSp  Parch     Fare Embarked   Family  Family_Sur_rate  \
0       3  22.0      1      0   7.2500        S   Braund              0.0   
1       3  29.0      1      0   7.0458        S   Braund              0.0   
2       1  38.0      1      0  71.2833        C  Cumings              1.0   

   Name_Length  Sex_male  Title_Miss  Title_Mr  Title_Mrs  
0           23         1           0         1          0  
1           25         1           0         1          0  
2           51         0           0         0          1

In [58]:
data['Family'] = data['SibSp'] + data['Parch'] + 1

In [59]:
data['Alone'] = data['Family'].apply(lambda x: 1 if x == 1 else 0)

In [60]:
data['Embarked'] = data['Embarked'].map({'C': 1, 'Q': 2, 'S': 3})

In [61]:
data.head(3)

Pclass   Age  SibSp  Parch     Fare  Embarked  Family  Family_Sur_rate  \
0       3  22.0      1      0   7.2500       3.0       2              0.0   
1       3  29.0      1      0   7.0458       3.0       2              0.0   
2       1  38.0      1      0  71.2833       1.0       2              1.0   

   Name_Length  Sex_male  Title_Miss  Title_Mr  Title_Mrs  Alone  
0           23         1           0         1          0      0  
1           25         1           0         1          0      0  
2           51         0           0         0          1      0

In [62]:
data.drop(['SibSp', 'Parch', 'Family'], axis=1, inplace= True)

In [77]:
data.head(3)

Pclass   Age     Fare  Embarked  Family_Sur_rate  Name_Length  Sex_male  \
0       3  22.0   7.2500       3.0              0.0           23         1   
1       3  29.0   7.0458       3.0              0.0           25         1   
2       1  38.0  71.2833       1.0              1.0           51         0   

   Title_Miss  Title_Mr  Title_Mrs  Alone  
0           0         1          0      0  
1           0         1          0      0  
2           0         0          1      0

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1079 entries, 0 to 1078
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Pclass           1079 non-null   int64  
 1   Age              1079 non-null   float64
 2   Fare             1079 non-null   float64
 3   Embarked         1077 non-null   float64
 4   Family_Sur_rate  1079 non-null   float64
 5   Name_Length      1079 non-null   int64  
 6   Sex_male         1079 non-null   uint8  
 7   Title_Miss       1079 non-null   uint8  
 8   Title_Mr         1079 non-null   uint8  
 9   Title_Mrs        1079 non-null   uint8  
 10  Alone            1079 non-null   int64  
dtypes: float64(4), int64(3), uint8(4)
memory usage: 111.7 KB


In [64]:
train_df = data.iloc[:891,:]  
train_df['Survived'] = x_Survived
test_df = data.iloc[891 :,:] 

C:\Users\Vinay\Anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


### Creating Train & Test Sets

In [65]:
X_train = train_df.drop('Survived', axis=1)
y_train = train_df['Survived']
X_test = test_df

In [66]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [67]:
min_max_scaler = MinMaxScaler()

In [68]:
X_train = min_max_scaler.fit_transform(X_train)

In [69]:
y_train = y_train.values

In [70]:
X_test = min_max_scaler.transform(X_test)

In [72]:
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, GradientBoostingClassifier

In [73]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, f1_score, roc_curve, roc_auc_score

In [74]:
from sklearn.model_selection import cross_val_predict

In [75]:
def train_vs_validation_error(model) :
    
    model.fit(X_train, y_train)
    predict_train = model.predict(X_train)
    print("Training Data")
    print(confusion_matrix(y_train, predict_train))
    print(f'Precision Score: {precision_score(y_train, predict_train)}')
    print(f'Recall Score: {recall_score(y_train, predict_train)}')
    print(f'F1 Score: {f1_score(y_train, predict_train)}')
    
    print('-'*50)
    
    print("Validation Data")
    predict_validation = cross_val_predict(model, X_train, y_train, cv = 10)
    y_score = cross_val_predict(model, X_train, y_train, cv = 5, method= "predict_proba")
    y_proba_score = y_score[:,1]
    print("Validation Confusion Matrix")
    print(confusion_matrix(y_train, predict_validation))
    print(f'Precision Score: {precision_score(y_train, predict_validation)}')
    print(f'Recall Score: {recall_score(y_train, predict_validation)}')
    print(f'F1 Score: {f1_score(y_train, predict_validation)}')
    
    print('-'*50)
    print(f'AUC: {roc_auc_score(y_train, y_proba_score)}')
    
    fpr_model, tpr_model, threshold = roc_curve(y_train, y_proba_score)

#### Random Forest

In [72]:
random_forest = RandomForestClassifier()

train_vs_validation_error(random_forest)

Training Data
[[548   1]
 [  3 339]]
Precision Score: 0.9970588235294118
Recall Score: 0.9912280701754386
F1 Score: 0.9941348973607038
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[484  65]
 [102 240]]
Precision Score: 0.7868852459016393
Recall Score: 0.7017543859649122
F1 Score: 0.7418856259659969
--------------------------------------------------
AUC: 0.8518252218280981


In [76]:
random_forest = RandomForestClassifier()

train_vs_validation_error(random_forest)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [138]:
random_forest = RandomForestClassifier()

train_vs_validation_error(random_forest)

Training Data
[[548   1]
 [  2 340]]
Precision Score: 0.9970674486803519
Recall Score: 0.9941520467836257
F1 Score: 0.9956076134699854
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[481  68]
 [ 93 249]]
Precision Score: 0.7854889589905363
Recall Score: 0.7280701754385965
F1 Score: 0.755690440060698
--------------------------------------------------
AUC: 0.8615691475196796


In [160]:
random_forest = RandomForestClassifier()

train_vs_validation_error(random_forest)

Training Data
[[548   1]
 [  2 340]]
Precision Score: 0.9970674486803519
Recall Score: 0.9941520467836257
F1 Score: 0.9956076134699854
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[487  62]
 [ 95 247]]
Precision Score: 0.7993527508090615
Recall Score: 0.7222222222222222
F1 Score: 0.7588325652841783
--------------------------------------------------
AUC: 0.8596757528307716


In [66]:
from sklearn.model_selection import GridSearchCV

In [141]:
param_grid = {'n_estimators' : [100, 300, 500], 'max_depth' : [7, 10, 15], 'max_features' : [0.5, 'sqrt', 'log2']}

In [142]:
grid_search = GridSearchCV(random_forest, param_grid= param_grid, cv= 5, verbose= 3)

In [143]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] max_depth=7, max_features=0.5, n_estimators=100 .................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  max_depth=7, max_features=0.5, n_estimators=100, score=0.827, total=   0.2s
[CV] max_depth=7, max_features=0.5, n_estimators=100 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=100, score=0.820, total=   0.2s

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s



[CV] max_depth=7, max_features=0.5, n_estimators=100 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=100, score=0.831, total=   0.2s
[CV] max_depth=7, max_features=0.5, n_estimators=100 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=100, score=0.815, total=   0.2s
[CV] max_depth=7, max_features=0.5, n_estimators=100 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=100, score=0.854, total=   0.2s
[CV] max_depth=7, max_features=0.5, n_estimators=300 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=300, score=0.827, total=   0.6s
[CV] max_depth=7, max_features=0.5, n_estimators=300 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=300, score=0.820, total=   0.5s
[CV] max_depth=7, max_features=0.5, n_estimators=300 .................
[CV]  max_depth=7, max_features=0.5, n_estimators=300, score=0.837, total=   0.6s
[CV] max_depth=7, max_features=0.5, n_estimators=300 .................
[CV]  max_

[CV]  max_depth=10, max_features=0.5, n_estimators=500, score=0.838, total=   1.2s
[CV] max_depth=10, max_features=0.5, n_estimators=500 ................
[CV]  max_depth=10, max_features=0.5, n_estimators=500, score=0.826, total=   1.2s
[CV] max_depth=10, max_features=0.5, n_estimators=500 ................
[CV]  max_depth=10, max_features=0.5, n_estimators=500, score=0.843, total=   1.0s
[CV] max_depth=10, max_features=0.5, n_estimators=500 ................
[CV]  max_depth=10, max_features=0.5, n_estimators=500, score=0.809, total=   1.0s
[CV] max_depth=10, max_features=0.5, n_estimators=500 ................
[CV]  max_depth=10, max_features=0.5, n_estimators=500, score=0.848, total=   1.0s
[CV] max_depth=10, max_features=sqrt, n_estimators=100 ...............
[CV]  max_depth=10, max_features=sqrt, n_estimators=100, score=0.827, total=   0.2s
[CV] max_depth=10, max_features=sqrt, n_estimators=100 ...............
[CV]  max_depth=10, max_features=sqrt, n_estimators=100, score=0.820, total

[CV]  max_depth=15, max_features=sqrt, n_estimators=100, score=0.792, total=   0.4s
[CV] max_depth=15, max_features=sqrt, n_estimators=100 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=100, score=0.848, total=   0.3s
[CV] max_depth=15, max_features=sqrt, n_estimators=300 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=300, score=0.821, total=   0.5s
[CV] max_depth=15, max_features=sqrt, n_estimators=300 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=300, score=0.826, total=   0.6s
[CV] max_depth=15, max_features=sqrt, n_estimators=300 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=300, score=0.837, total=   0.6s
[CV] max_depth=15, max_features=sqrt, n_estimators=300 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=300, score=0.792, total=   0.6s
[CV] max_depth=15, max_features=sqrt, n_estimators=300 ...............
[CV]  max_depth=15, max_features=sqrt, n_estimators=300, score=0.837, 

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 135 out of 135 | elapsed:  1.3min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [144]:
grid_search.best_params_

{'max_depth': 10, 'max_features': 'log2', 'n_estimators': 300}

In [145]:
grid_results = grid_search.cv_results_

In [146]:
for mean_score, param in zip(grid_results['mean_test_score'], grid_results['params']) :
    print(mean_score, param)

0.8294080723118448 {'max_depth': 7, 'max_features': 0.5, 'n_estimators': 100}
0.829408072311845 {'max_depth': 7, 'max_features': 0.5, 'n_estimators': 300}
0.8294017952419811 {'max_depth': 7, 'max_features': 0.5, 'n_estimators': 500}
0.8237900947837551 {'max_depth': 7, 'max_features': 'sqrt', 'n_estimators': 100}
0.8316552633230808 {'max_depth': 7, 'max_features': 'sqrt', 'n_estimators': 300}
0.8271671583704727 {'max_depth': 7, 'max_features': 'sqrt', 'n_estimators': 500}
0.8226727763480008 {'max_depth': 7, 'max_features': 'log2', 'n_estimators': 100}
0.8271797125102003 {'max_depth': 7, 'max_features': 'log2', 'n_estimators': 300}
0.8327600276191074 {'max_depth': 7, 'max_features': 'log2', 'n_estimators': 500}
0.8372544096415794 {'max_depth': 10, 'max_features': 0.5, 'n_estimators': 100}
0.8316427091833531 {'max_depth': 10, 'max_features': 0.5, 'n_estimators': 300}
0.8327663046889711 {'max_depth': 10, 'max_features': 0.5, 'n_estimators': 500}
0.8350260498399347 {'max_depth': 10, 'max_fe

In [147]:
feature_importance = grid_search.best_estimator_.feature_importances_

features = pd.DataFrame(data= feature_importance.reshape(1,-1), columns= X_train.columns)

In [148]:
features

Pclass       Age      Fare  Embarked  Name_Length  Sex_male  Title_Miss  \
0  0.09128  0.131807  0.164467  0.027914     0.137288  0.110488    0.035812   

   Title_Mr  Title_Mrs    Family     Alone  
0  0.181698   0.036148  0.072655  0.010443

In [149]:
tuned_random_forest = RandomForestClassifier(max_depth= 10, max_features= 'log2', n_estimators= 300)

In [161]:
train_vs_validation_error(tuned_random_forest)

Training Data
[[545   4]
 [ 39 303]]
Precision Score: 0.9869706840390879
Recall Score: 0.8859649122807017
F1 Score: 0.9337442218798152
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[498  51]
 [ 96 246]]
Precision Score: 0.8282828282828283
Recall Score: 0.7192982456140351
F1 Score: 0.7699530516431925
--------------------------------------------------
AUC: 0.8677047049925969


#### Bagging

In [151]:
bagging = BaggingClassifier()

train_vs_validation_error(bagging)

Training Data
[[544   5]
 [ 12 330]]
Precision Score: 0.9850746268656716
Recall Score: 0.9649122807017544
F1 Score: 0.9748892171344165
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[484  65]
 [107 235]]
Precision Score: 0.7833333333333333
Recall Score: 0.6871345029239766
F1 Score: 0.7320872274143303
--------------------------------------------------
AUC: 0.8472608357566656


#### Gradient Boosting

In [152]:
gradient_boosting = GradientBoostingClassifier()

train_vs_validation_error(gradient_boosting)

Training Data
[[518  31]
 [ 60 282]]
Precision Score: 0.9009584664536742
Recall Score: 0.8245614035087719
F1 Score: 0.8610687022900764
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[490  59]
 [103 239]]
Precision Score: 0.802013422818792
Recall Score: 0.6988304093567251
F1 Score: 0.7468750000000001
--------------------------------------------------
AUC: 0.8672866136196593


#### XGBoost

In [164]:
from xgboost import XGBClassifier

xgboost = XGBClassifier()

train_vs_validation_error(xgboost)

Training Data
[[514  35]
 [ 67 275]]
Precision Score: 0.8870967741935484
Recall Score: 0.804093567251462
F1 Score: 0.843558282208589
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[490  59]
 [104 238]]
Precision Score: 0.8013468013468014
Recall Score: 0.695906432748538
F1 Score: 0.7449139280125195
--------------------------------------------------
AUC: 0.8688817520425228


In [165]:
help(XGBClassifier)

Help on class XGBClassifier in module xgboost.sklearn:

class XGBClassifier(XGBModel, sklearn.base.ClassifierMixin)
 |  XGBClassifier(max_depth=3, learning_rate=0.1, n_estimators=100, verbosity=1, silent=None, objective='binary:logistic', booster='gbtree', n_jobs=1, nthread=None, gamma=0, min_child_weight=1, max_delta_step=0, subsample=1, colsample_bytree=1, colsample_bylevel=1, colsample_bynode=1, reg_alpha=0, reg_lambda=1, scale_pos_weight=1, base_score=0.5, random_state=0, seed=None, missing=None, **kwargs)
 |  
 |  Implementation of the scikit-learn API for XGBoost classification.
 |  
 |  Parameters
 |  ----------
 |  max_depth : int
 |      Maximum tree depth for base learners.
 |  learning_rate : float
 |      Boosting learning rate (xgb's "eta")
 |  n_estimators : int
 |      Number of trees to fit.
 |  verbosity : int
 |      The degree of verbosity. Valid values are 0 (silent) - 3 (debug).
 |  silent : boolean
 |      Whether to print messages while running boosting. Deprecat

In [173]:
param_grid_xg = {'n_estimators' : [300, 500, 1000, 1500],  'learning_rate' : [ 0.02, 0.05,1]}

In [174]:
grid_search_xgboost = GridSearchCV(xgboost, param_grid= param_grid_xg, cv = 5, verbose=3)

In [175]:
grid_search_xgboost.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] learning_rate=0.02, n_estimators=300 ............................
[CV]  learning_rate=0.02, n_estimators=300, score=0.788, total=   0.2s
[CV] learning_rate=0.02, n_estimators=300 ............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV]  learning_rate=0.02, n_estimators=300, score=0.820, total=   0.2s
[CV] learning_rate=0.02, n_estimators=300 ............................
[CV]  learning_rate=0.02, n_estimators=300, score=0.831, total=   0.1s
[CV] learning_rate=0.02, n_estimators=300 ............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV]  learning_rate=0.02, n_estimators=300, score=0.798, total=   0.2s
[CV] learning_rate=0.02, n_estimators=300 ............................
[CV]  learning_rate=0.02, n_estimators=300, score=0.854, total=   0.2s
[CV] learning_rate=0.02, n_estimators=500 ............................
[CV]  learning_rate=0.02, n_estimators=500, score=0.821, total=   0.2s
[CV] learning_rate=0.02, n_estimators=500 ............................
[CV]  learning_rate=0.02, n_estimators=500, score=0.826, total=   0.3s
[CV] learning_rate=0.02, n_estimators=500 ............................
[CV]  learning_rate=0.02, n_estimators=500, score=0.826, total=   0.2s
[CV] learning_rate=0.02, n_estimators=500 ............................
[CV]  learning_rate=0.02, n_estimators=500, score=0.815, total=   0.2s
[CV] learning_rate=0.02, n_estimators=500 ............................
[CV]  learning_rate=0.02, n_estimators=500, score=0.848, total=   0.3s
[CV] learning_rate=0.02, n_estimators=1000 ...........................
[CV]  

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:   24.5s finished


GridSearchCV(cv=5, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=None,
             param_grid={'learning_rate': [0.02, 0.05, 1],
                         'n_estimators': [300, 500, 1000, 1500]},
             pre_dispatch='2*n_jobs', refit=True, re

In [176]:
grid_search_xgboost.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [178]:
optimized_xgboost = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [179]:
train_vs_validation_error(optimized_xgboost)

Training Data
[[527  22]
 [ 47 295]]
Precision Score: 0.9305993690851735
Recall Score: 0.8625730994152047
F1 Score: 0.8952959028831562
--------------------------------------------------
Validation Data
Validation Confusion Matrix
[[495  54]
 [100 242]]
Precision Score: 0.8175675675675675
Recall Score: 0.7076023391812866
F1 Score: 0.7586206896551724
--------------------------------------------------
AUC: 0.8689137080710276


In [183]:
optimized_xgboost.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [184]:
predicts = optimized_xgboost.predict(X_test)

ValueError: feature_names mismatch: ['Pclass', 'Age', 'Fare', 'Embarked', 'Name_Length', 'Sex_male', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Family', 'Alone'] ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10']
expected Name_Length, Title_Mrs, Title_Miss, Pclass, Fare, Alone, Title_Mr, Embarked, Age, Family, Sex_male in input data
training data did not have the following fields: f1, f2, f6, f3, f7, f4, f9, f8, f10, f5, f0