In [1]:
import pandas as pd
import numpy as np

In [2]:
%%HTML
<style type="text/css">
table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}

# Data Loading 

In [3]:
data = pd.read_csv(r'data.csv')

In [4]:
data.head()

Survived     Fare  Cabin  Title  Name Length  Fam_Large  Fam_Small  Tic_A4  \
0       0.0   7.2500      0      0           23          0          1       0   
1       1.0  71.2833      1      4           51          0          1       0   
2       1.0   7.9250      0      3           22          0          0       0   
3       1.0  53.1000      1      4           44          0          1       0   
4       0.0   8.0500      0      0           24          0          0       0   

   Tic_A5  Tic_AQ3  ...  Sex_male  Em_Q  Em_S  Age_10-20  Age_20-30  \
0       1        0  ...         1     0     1          0          1   
1       0        0  ...         0     0     0          0          0   
2       0        0  ...         0     0     1          0          1   
3       0        0  ...         0     0     1          0          0   
4       0        0  ...         1     0     1          0          0   

   Age_30-40  Age_40-50  Age_50-60  Age_60-70  Age_80-90  
0          0          0          0          0          0  
1          1          0          0          0          0  
2          0          0          0          0          0  
3          1          0          0          0          0  
4          1          0          0          0          0  

[5 rows x 55 columns]

In [5]:
data_2 = data

In [6]:
data_2.columns

Index(['Survived', 'Fare', 'Cabin', 'Title', 'Name Length', 'Fam_Large',
       'Fam_Small', 'Tic_A4', 'Tic_A5', 'Tic_AQ3', 'Tic_AQ4', 'Tic_AS',
       'Tic_C', 'Tic_CA', 'Tic_CASOTON', 'Tic_FC', 'Tic_FCC', 'Tic_Fa',
       'Tic_LINE', 'Tic_LP', 'Tic_No', 'Tic_PC', 'Tic_PP', 'Tic_PPP', 'Tic_SC',
       'Tic_SCA3', 'Tic_SCA4', 'Tic_SCAH', 'Tic_SCOW', 'Tic_SCPARIS',
       'Tic_SCParis', 'Tic_SOC', 'Tic_SOP', 'Tic_SOPP', 'Tic_SOTONO2',
       'Tic_SOTONOQ', 'Tic_SP', 'Tic_STONO', 'Tic_STONO2', 'Tic_STONOQ',
       'Tic_SWPP', 'Tic_WC', 'Tic_WEP', 'Pc_2', 'Pc_3', 'Sex_male', 'Em_Q',
       'Em_S', 'Age_10-20', 'Age_20-30', 'Age_30-40', 'Age_40-50', 'Age_50-60',
       'Age_60-70', 'Age_80-90'],
      dtype='object')

In [7]:
for col in data_2.columns :
    
    if col.split('_')[0] == 'Tic' :
        data_2.drop(col, axis=1, inplace= True)

In [8]:
data_2.columns

Index(['Survived', 'Fare', 'Cabin', 'Title', 'Name Length', 'Fam_Large',
       'Fam_Small', 'Pc_2', 'Pc_3', 'Sex_male', 'Em_Q', 'Em_S', 'Age_10-20',
       'Age_20-30', 'Age_30-40', 'Age_40-50', 'Age_50-60', 'Age_60-70',
       'Age_80-90'],
      dtype='object')

# Model Selection

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix

In [10]:
#write a function to evaluate your model

def evaluate_accuracy(model) :
    
    print(str(model))
    #On Training Data
    model.fit(X_train, y_train)
    predict_train = model.predict(X_train)
    training_accuracy = accuracy_score(y_train, predict_train)
    print("Training Data")
    print(confusion_matrix(y_train, predict_train))
    print(f'Accuracy Score: {training_accuracy}')
    print('-'*50)
    print("Validation Data")
    predict_score = cross_val_score(model, X_train, y_train, cv = 10, scoring = 'accuracy')
    validation_accuracy = predict_score.mean()
    print(f'Accuracy Score: {validation_accuracy}')
    print('')
    return training_accuracy, validation_accuracy

In [11]:
#spliting back the data into training and test data
training_data = data_2.iloc[:891,:]  
test_data = data_2.iloc[891 :,:] 
test_data.drop('Survived', axis =1, inplace =True)

X_train = training_data.drop('Survived', axis = 1).values
y_train = training_data['Survived'].values

X_test = test_data.values

display(X_train.shape)
display(y_train.shape)
display(X_test.shape)

C:\Users\91954\anaconda3\envs\tf_gpu\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


(891, 18)

(891,)

(418, 18)

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
#create a scaling object
scaler = MinMaxScaler()

#fit the object only on training data and not test data
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## SVC

In [169]:
from sklearn.svm import SVC

In [170]:
svc_classifier = SVC(random_state= 42)

In [125]:
evaluate_accuracy(svc_classifier)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)
Training Data
[[498  51]
 [ 90 252]]
Accuracy Score: 0.8417508417508418
--------------------------------------------------
Validation Data
Accuracy Score: 0.8283021223470662



(0.8417508417508418, 0.8283021223470662)

In [171]:
#with data 2
evaluate_accuracy(svc_classifier)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)
Training Data
[[502  47]
 [ 88 254]]
Accuracy Score: 0.8484848484848485
--------------------------------------------------
Validation Data
Accuracy Score: 0.821585518102372



(0.8484848484848485, 0.821585518102372)

In [126]:
svc_classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [179]:
param_grid = {'C' : [0.1, 1, 3, 10], 'gamma' : [0.001,0.03, 0.01,0.1, 1, 'scale']}

In [180]:
from sklearn.model_selection import GridSearchCV

In [181]:
svc_grid = GridSearchCV(svc_classifier, param_grid= param_grid, scoring= 'accuracy', n_jobs= -1, cv = 10 )

In [182]:
svc_grid.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=42, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [0.1, 1, 3, 10],
                         'gamma': [0.001, 0.03, 0.01, 0.1, 1, 'scale']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [183]:
svc_grid.best_params_

{'C': 3, 'gamma': 0.1}

In [184]:
svc_grid.best_score_

0.8339076154806492

In [185]:
sub = svc_grid.predict(X_test)

In [62]:
submission = pd.read_csv('gender_submission.csv')

In [64]:
submission['Survived'] = sub

In [66]:
submission['Survived'] = submission['Survived'].astype('int16')

In [68]:
submission.to_csv('New SVC Model.txt', index= False)

## GBM

In [186]:
from sklearn.ensemble import GradientBoostingClassifier

In [187]:
gbc_classifier = GradientBoostingClassifier(random_state= 42)

In [188]:
evaluate_accuracy(gbc_classifier)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
Training Data
[[527  22]
 [ 56 286]]
Accuracy Score: 0.9124579124579124
--------------------------------------------------
Validation Data
Accuracy Score: 0.83167290886392



(0.9124579124579124, 0.83167290886392)

In [189]:
param_grid_gbc = {'max_depth' : [3,5,6,7,8], 'min_samples_leaf' : [3,5,7,9]}

In [190]:
gbc_grid = GridSearchCV(gbc_classifier, param_grid= param_grid_gbc, n_jobs= -1, cv= 10,)

In [191]:
gbc_grid.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                                  criterion='friedman_mse',
                                                  init=None, learning_rate=0.1,
                                                  loss='deviance', max_depth=3,
                                                  max_features=None,
                                                  max_leaf_nodes=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                                  n_estimators=100,
                                                  n_iter_no_change=None,
        

In [192]:
gbc_grid.best_params_

{'max_depth': 5, 'min_samples_leaf': 7}

In [193]:
gbc_grid.best_score_

0.848501872659176

In [194]:
sub = gbc_grid.predict(X_test)

In [195]:
submission['Survived'] = sub

In [196]:
submission['Survived'] = submission['Survived'].astype('int8')

In [197]:
submission.to_csv('New Gradient Boosting Classifer Pred.txt', index= False)

## Ridge Classifier

In [198]:
from sklearn.linear_model import RidgeClassifier

In [199]:
ridge_clf = RidgeClassifier(random_state= 42)

In [200]:
evaluate_accuracy(ridge_clf)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=42, solver='auto',
                tol=0.001)
Training Data
[[487  62]
 [ 91 251]]
Accuracy Score: 0.8282828282828283
--------------------------------------------------
Validation Data
Accuracy Score: 0.8260424469413232



(0.8282828282828283, 0.8260424469413232)

In [137]:
param_grid_ridge = {'normalize' : [True, False], 'alpha' : [0.1,1.0, 3.0, 10.0]}

In [138]:
ridge_grid = GridSearchCV(ridge_clf, param_grid= param_grid_ridge, cv= 10, n_jobs= -1)

In [139]:
ridge_grid.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=RidgeClassifier(alpha=1.0, class_weight=None,
                                       copy_X=True, fit_intercept=True,
                                       max_iter=None, normalize=False,
                                       random_state=42, solver='auto',
                                       tol=0.001),
             iid='deprecated', n_jobs=-1,
             param_grid={'alpha': [0.1, 1.0, 3.0, 10.0],
                         'normalize': [True, False]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [140]:
ridge_grid.best_params_

{'alpha': 1.0, 'normalize': False}

In [141]:
ridge_grid.best_score_

0.8238077403245944

## XGBoost

In [14]:
from xgboost import XGBClassifier

In [15]:
xg_clf = XGBClassifier(n_estimators= 500, verbosity= True, learning_rate = 0.1, max_depth = 6)

In [173]:
evaluate_accuracy(xg_clf)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)
Training Data
[[510  39]
 [ 65 277]]
Accuracy Score: 0.8832772166105499
--------------------------------------------------
Validation Data
Accuracy Score: 0.8294132334581773



(0.8832772166105499, 0.8294132334581773)

In [216]:
param_grid_xg = {'max_depth' : [1,5,7], 'learning_rate' : [0.1, 0.03, 0.01],
                'n_estimators' : [100, 300, 500, 750, 1000]}

In [217]:
grid_xg = GridSearchCV(xg_clf, param_grid_xg, cv = 10, n_jobs= -1)

In [218]:
grid_xg.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.03, 0.01],
                         'max_depth': [1, 5, 7],
                         'n_estimators': [100, 300, 500, 750, 1000]}

In [219]:
grid_xg.best_params_

{'learning_rate': 0.03, 'max_depth': 5, 'n_estimators': 300}

In [220]:
grid_xg.best_score_

0.8417727840199749

In [222]:
preds = grid_xg.predict(X_test)

In [223]:
submission['Survived'] = preds
submission['Survived'] = submission['Survived'].astype('int8')

submission.to_csv('New XGBoost.txt', index = False)

In [221]:
feature_imp = list(grid_xg.feature_importances_)

AttributeError: 'GridSearchCV' object has no attribute 'feature_importances_'

In [175]:
len(feature_imp)

18

In [176]:
feature_importance = pd.DataFrame(data = feature_imp, index= training_data.drop('Survived',axis =1).columns, columns= ['Imp'])

In [177]:
feature_importance = feature_importance.sort_values(by = 'Imp', ascending = False)

In [178]:
feature_importance

Imp
Title        0.363869
Pc_3         0.190388
Cabin        0.083721
Fam_Large    0.068077
Sex_male     0.052528
Age_30-40    0.041365
Em_S         0.032204
Age_60-70    0.030526
Fare         0.029116
Name Length  0.021366
Pc_2         0.019280
Age_20-30    0.017589
Age_40-50    0.015764
Age_50-60    0.013997
Fam_Small    0.010623
Age_10-20    0.009588
Em_Q         0.000000
Age_80-90    0.000000